# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build temper nice_nano_v2 nice_view'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view_adapter nice_view","temper_right nice_view_adapter nice_view"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY", "#define MIRYOKU_EXTRA_COLEMAKDH", "#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y", "CONFIG_ZMK_MOUSE=y"]'
